repos:
  - repo: local
    hooks:
      - id: sort_pyproject
        name: sort_pyproject
        entry: toml-sort -i --sort-table-keys --sort-inline-tables
        language: python
        files: ^pyproject\.toml$
        additional_dependencies: ["toml-sort==0.23.1"]
      - id: generate-kinetic-laws
        name: generate-kinetic-laws
        entry: python kinetic-laws/generate.py
        language: python
        files: ^kinetic-laws/
        additional_dependencies: ["jinja2>=3.1.6"]
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff-format # formatter
        types_or: [python, pyi, jupyter, toml]
      - id: ruff # linter
        types_or: [python, pyi, jupyter, toml]
        args: [--fix]
