name: Ruff
on:
  push:
    paths:
      - 'catalax/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - 'catalax/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/lint.yml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: './catalax'
      - uses: chartboost/ruff-action@v1
        with:
          src: './tests'
